<CustomDialogContent>:
    orientation: 'vertical'
    spacing: dp(20)

    MDTextField:
        hint_text: 'E-mail'
        helper_text: 'Your personal e-mail here'
        helper_text_mode: 'on_focus'
        icon_right: 'email'
        color_mode: 'accent'

    MDTextField:
        hint_text: 'Password'
        helper_text: 'Your password here'
        helper_text_mode: 'on_focus'
        icon_right: 'lock'
        color_mode: 'accent'
        password: True
