<MDBottomSheetScreen>:
    MDBoxLayout:
        orientation: 'vertical'

        MDToolbar:
            pos_hint: {'top': 1}
            id: toolbar
            elevation: 10
            title: 'Navigation Drawer'

        MDFloatLayout:
            MDIconButton:
                pos_hint: {'center_x': .5, 'center_y': .5}
                icon: 'share'
                on_release:
                    app.show_share_bottom_sheet()